services:
  stockfish:
    build:
      context: ./stockfish
      dockerfile: Dockerfile
    container_name: stockfish
    ports:
      - "4001:4001"
    networks:
      - engine
      
  actix:
    build:
      context: ./actix
      dockerfile: Dockerfile
    container_name: actix
    ports:
      - "4000:4000"
    depends_on:
      - stockfish
    networks:
      - engine

networks:
  engine:
    driver: bridge