apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockfish
  namespace: stockfish
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stockfish
  template:
    metadata:
      labels:
        app: stockfish
    spec:
      containers:
      - name: stockfish
        image: ${ECR_REPO_URL}/stockfish:latest
        ports:
        - containerPort: 4001
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"