apiVersion: apps/v1
kind: Deployment
metadata:
  name: axum
  namespace: stockfish
spec:
  replicas: 2
  selector:
    matchLabels:
      app: axum
  template:
    metadata:
      labels:
        app: axum
    spec:
      containers:
      - name: axum
        image: ${ECR_REPO_URL}/axum:latest
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"