// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";

export type MatchResponse = { "result": "Ok", "value": { game_id: string, color: Color, } } | { "result": "Err", "value": string };
