// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientMessage = { "kind": "Auth", "value": { game_id: string, user_id: string, } } | { "kind": "Move", "value": string } | { "kind": "Ping" };
