// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InitBody = { game_id: string, white_user_id: string, black_user_id: string, };
