// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Error } from "./Error";
import type { Outcome } from "./Outcome";

export type ServerMessage = { "Move": string } | { "GameEnd": Outcome } | { "Error": Error } | "AuthSuccess" | { "MoveHistory": Array<string> };
