---
services:
  chesscloud-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_GOOGLE_AUTH_ENDPOINT: ${NEXT_PUBLIC_GOOGLE_AUTH_ENDPOINT}
        NEXT_PUBLIC_ENGINE_API_URL:       ${NEXT_PUBLIC_ENGINE_API_URL}
        NEXT_PUBLIC_WS_SERVER_URL:        ${NEXT_PUBLIC_WS_SERVER_URL}
        NEXT_PUBLIC_MATCHMAKING_SERVER_URL: ${NEXT_PUBLIC_MATCHMAKING_SERVER_URL}
    env_file:
      - .env
    ports:
      - '3000:3000'
